# Generated by Django 4.0.4 on 2022-05-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_cafe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.location'),
        ),
    ]
