# Generated by Django 4.0.4 on 2022-05-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_waiter_cafe_waiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='image',
            field=models.ImageField(default='image', upload_to='images'),
            preserve_default=False,
        ),
    ]
