# Generated by Django 4.0.4 on 2022-05-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_waiter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='waiters',
        ),
        migrations.AddField(
            model_name='waiter',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.cafe'),
            preserve_default=False,
        ),
    ]
