# Generated by Django 4.0.4 on 2022-05-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_remove_cafe_waiters_waiter_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='cafe',
        ),
        migrations.AddField(
            model_name='cafe',
            name='waiters',
            field=models.ManyToManyField(blank=True, to='tips.waiter'),
        ),
    ]
