# Generated by Django 4.0.4 on 2022-05-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_remove_waiter_cafe_cafe_waiters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='waiters',
        ),
        migrations.AddField(
            model_name='waiter',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.cafe'),
        ),
    ]
