# Generated by Django 4.0.4 on 2022-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_remove_cafe_waiters_waiter_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='password',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
