# Generated by Django 4.0.4 on 2022-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0011_waiter_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiter',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='waiter',
            name='password2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
