# Generated by Django 4.0.4 on 2022-05-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_rename_password_waiter_password1_waiter_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='password2',
        ),
    ]
