# Generated by Django 4.0.4 on 2022-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0013_remove_waiter_password1_remove_waiter_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
