# Generated by Django 4.0.4 on 2022-05-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0016_remove_waiter_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='name',
        ),
    ]
