# Generated by Django 4.0.4 on 2022-05-20 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips', '0018_waiterprofiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaiterProfiles',
            new_name='WaiterProfile',
        ),
    ]
