# Generated by Django 4.0.4 on 2022-05-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0020_customerprofile_delete_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='description',
        ),
    ]
