# Generated by Django 4.0.4 on 2022-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0021_remove_customerprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
