# Generated by Django 4.0.4 on 2022-05-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0022_customerprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='balance',
            field=models.FloatField(default=0, null=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waiterprofile',
            name='balance',
            field=models.FloatField(default=0, null=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
