# Generated by Django 4.0.4 on 2022-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0023_customerprofile_balance_waiterprofile_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
