# Generated by Django 4.0.4 on 2022-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0025_alter_customerprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
