# Generated by Django 4.0.4 on 2022-05-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0029_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='message',
            field=models.TextField(blank=True, default='No additional information'),
        ),
    ]
