# Generated by Django 4.0.4 on 2022-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0030_alter_join_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, default='No additional information'),
        ),
    ]
