# Generated by Django 4.0.4 on 2022-06-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0031_transaction_balance_transaction_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='balance',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reciever',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='tips.waiterprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tips.customerprofile'),
        ),
    ]
