# Generated by Django 4.0.4 on 2022-06-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0035_alter_transaction_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='waiterprofile',
            name='balance',
        ),
    ]
