# Generated by Django 4.0.4 on 2022-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0038_alter_customerprofile_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterprofile',
            name='image',
            field=models.ImageField(default=0, unique=True, upload_to='images'),
        ),
    ]
