# Generated by Django 4.0.4 on 2022-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0039_alter_waiterprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterprofile',
            name='image',
            field=models.ImageField(blank=True, default=0, unique=True, upload_to='images'),
        ),
    ]
