# Generated by Django 4.0.4 on 2022-06-03 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0040_alter_waiterprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
